vTube/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('video_tube.urls',namespace='video_tube'))
]

video_tube/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.decorators import login_required
app_name = 'video_tube'
urlpatterns = [
    path('',login_required(views.Home.as_view(),login_url='/login/'), name='home'),
    path('video/id=<int:pk>/', views.video, name='video'),
    path('user/id=<int:pk>/', views.Userprofile, name='profile'),
    path('categorey/id=<int:pk>/',login_required(views.Category.as_view(),login_url='/login/'),name='category'),
    path('profile/',views.profile,name='profile'),
    path('upload/',login_required(views.UploadView.as_view(),login_url='/login/'),name='upload'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',login_required(views.logoutView,login_url='/login/'),name='logout'),
    path('signup/',views.SignUpView.as_view(),name='signup')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_tube/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserModel(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/',default='media/user.png')
    def __str__(self):
        return self.user.username



class Categorey(models.Model):
    name=models.CharField(max_length=20,null=True)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name='Categorey'
        verbose_name_plural='Categories'

class Video(models.Model):
    title=models.CharField(max_length=100)
    categorey=models.ForeignKey(Categorey,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    thumbnail=models.ImageField(upload_to='media/')
    video=models.FileField(upload_to='media/')
    user=models.ForeignKey(UserModel,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='Video'
        verbose_name_plural='Videos'

class Commment(models.Model):
    comment_text=models.TextField(max_length=200)
    date=models.DateTimeField(auto_now_add=True)
    video=models.ForeignKey(Video,on_delete=models.CASCADE)
    user=models.ForeignKey(UserModel,on_delete=models.CASCADE)

    def __str__(self):
        return self.comment_text
    class Meta:
        verbose_name='Comment'
        verbose_name_plural='Comments'

class Reply(models.Model):
    comment_text=models.TextField(max_length=200)
    comment=models.ForeignKey(Commment,on_delete=models.CASCADE)
    user=models.ForeignKey(UserModel,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_text
    class Meta:
        verbose_name='Reply'
        verbose_name_plural='Replies'

class Like(models.Model):
    video=models.ForeignKey(Video,on_delete=models.CASCADE)
    user=models.ForeignKey(UserModel,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.user.username
    class Meta:
        verbose_name='Like'
        verbose_name_plural='Likes'

class Unlike(models.Model):
    video=models.ForeignKey(Video,on_delete=models.CASCADE)
    user=models.ForeignKey(UserModel,on_delete=models.CASCADE)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return  self.user.user.username

    class Meta:
        verbose_name='Unlike'
        verbose_name_plural='Unlikes'


class Views(models.Model):
    video=models.ForeignKey(Video,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

video_tube/forms.py
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Video,UserModel
from django import forms
from django.forms import ModelForm

class VideoForm(ModelForm):
    class Meta:
        model=Video
        fields=['title','categorey','thumbnail','video']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'categorey':forms.Select(attrs={'class':'form-control'}),


        }
        help_texts={
            'video':'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***The video not more than 15 seconds long'
        }
        error_messages={}
        labels={
            'title':'Enter the title of the video :',
            'categorey':'Select the category ',
            'thumbnail':'Select the thumbnail ',
            'video':'Select the video ',
        }
class ImageForm(ModelForm):
    class Meta:
        model=UserModel
        forms=['image']
        exclude=['user']
        labels={
            'image':'please select profile image'
        }


class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ['username','password1','password2']
        model = get_user_model()
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),

        }

video_tube/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import VideoForm,ImageForm,UserCreateForm
from .models import Video,Categorey,Like,Unlike,Commment,Reply,Views,UserModel
# Create your views here.

class Home(View):
    def get(self,request,*args,**kwargs):
        user=User.objects.get(id=request.user.id)
        if not UserModel.objects.filter(user=user):
            UserModel.objects.create(user=user)
        videos=Video.objects.all()
        categories=Categorey.objects.all()
        videos_info=[]
        for vid in videos:
            likes=Like.objects.filter(video=vid).count()
            views=Views.objects.filter(video=vid).count()
            video={
                'video':vid,
                'likes':likes,
                'views':views
            }
            videos_info.append(video)

        context={
            'videos':videos_info,
            'categories':categories
        }
        return render(request,'video_tube/home.html',context)
@login_required(login_url='/login/')
def video(request,pk):

    user=User.objects.get(pk=request.user.id)
    video=Video.objects.get(id=pk)
    cat=video.categorey
    categorey_videos=Video.objects.filter(categorey=cat).all()
    if not Views.objects.filter(user=user,video=video):
        Views.objects.create(user=user,video=video)
    profile=UserModel.objects.get(user=user)
    print(profile)
    if request.method=='POST':

        if 'like' in request.POST:
            if Unlike.objects.filter(video=video, user=profile):
                l = Unlike.objects.filter(video=video, user=profile)
                l.delete()
                return HttpResponseRedirect(f"/video/id={pk}")
            else:
                if not Like.objects.filter(video=video, user=profile):
                    Like.objects.create(video=video, user=profile)
                    return HttpResponseRedirect(f"/video/id={pk}")
                else:
                    l = Like.objects.filter(video=video, user=profile)
                    l.delete()
                    return HttpResponseRedirect(f"/video/id={pk}")
        elif 'unlike' in request.POST:
            if Like.objects.filter(video=video,user=profile):
                l = Like.objects.filter(video=video, user=profile)
                l.delete()
                return HttpResponseRedirect(f"/video/id={pk}")
            else:
                if not Unlike.objects.filter(video=video, user=profile):
                    Unlike.objects.create(video=video, user=profile)
                    return HttpResponseRedirect(f"/video/id={pk}")
                else:
                    l = Unlike.objects.filter(video=video, user=profile)
                    l.delete()
                    return HttpResponseRedirect(f"/video/id={pk}")
        elif 'comment' in request.POST:

            comment_txt=request.POST.get('comment_text')
            if not comment_txt.strip()=='':
                Commment.objects.create(comment_text=comment_txt,video=video,user=profile)
                return HttpResponseRedirect(f"/video/id={pk}")
        elif 'reply' in request.POST:
            comment_id=request.POST.get('comment_id')
            reply_text=request.POST.get('comment_reply')
            comment=Commment.objects.get(id=comment_id)
            reply=Reply.objects.create(comment=comment,user=profile,comment_text=reply_text)
            return HttpResponseRedirect(f"/video/id={pk}")


    likes=Like.objects.filter(video=video).count()
    unlikes=Unlike.objects.filter(video=video).count()
    views=Views.objects.filter(video=video).count()
    comments=Commment.objects.filter(video=video)
    comp_comments=[]
    for comment in comments:
        replies=Reply.objects.filter(comment=comment)
        c={
            'comment':comment,
            'reply':replies
        }
        comp_comments.append(c)
    context={
        'video':video,
        'likes':likes,
        'unlikes':unlikes,
        'views':views,
        'related_videos':categorey_videos,
        'comments':comp_comments,
        'total_comments':comments.count()
    }

    return render(request, 'video_tube/video_by_id.html',context)

class Category(View):
    def get(self,request,*args,**kwargs):
        id = self.kwargs.get('pk')
        cat=Categorey.objects.filter(id=id)
        cat_name=None
        for x in cat:
            cat_name=x
        videos=Video.objects.filter(categorey=cat_name)
        videos_info = []
        for vid in videos:
            likes = Like.objects.filter(video=vid).count()
            views=Views.objects.filter(video=vid).count()
            video = {
                'video': vid,
                'likes': likes,
                'views':views
            }
            videos_info.append(video)

        context = {
            'videos': videos_info,

        }

        return render(request,'video_tube/category_wise.html',context)
@login_required(login_url='/login/')
def Userprofile(request,pk):
    profile=UserModel.objects.get(id=pk)
    videos=Video.objects.filter(user=profile)
    total_likes=0
    total_views=0
    videos_info = []
    for vid in videos:
        likes = Like.objects.filter(video=vid).count()
        views = Views.objects.filter(video=vid).count()
        total_likes=total_likes+likes
        total_views=total_views+views
        video = {
            'video': vid,
            'likes': likes,
            'views': views
        }
        videos_info.append(video)
    context={
        'videos':videos_info,
        'total_video':videos.count(),
        'user':profile,
        'total_likes':total_likes,
        'total_views':total_views,

    }
    return render(request,'video_tube/user_profile.html',context)
@login_required(login_url='/login/')
def profile(request):
    user=request.user.id
    user=User.objects.get(id=user)
    profile=UserModel.objects.get(user=user)
    videos=Video.objects.filter(user=profile)
    total_likes=0
    total_views=0
    videos_info = []
    for vid in videos:
        likes = Like.objects.filter(video=vid).count()
        views = Views.objects.filter(video=vid).count()
        total_likes=total_likes+likes
        total_views=total_views+views
        video = {
            'video': vid,
            'likes': likes,
            'views': views
        }
        videos_info.append(video)
    if request.method=='POST':
        if 'edit' in request.POST:
            form = ImageForm(request.POST, request.FILES,instance=profile)
            if form.is_valid():
                prof = form.save(commit=False)
                prof.user = user
                prof.save()

    context={
        'videos':videos_info,
        'total_video':videos.count(),
        'user':profile,
        'total_likes':total_likes,
        'total_views':total_views,
        'change_image_form':ImageForm(instance=profile)
    }
    return render(request,'video_tube/my_profile.html',context)

class UploadView(View):
    def post(self,request,*args,**kwargs):
        user = request.user.id
        user = User.objects.get(id=user)
        user_profile = UserModel.objects.get(user=user)
        error=True
        if 'upload' in request.POST:

            if request.method == 'POST':
                form = VideoForm(request.POST, request.FILES)
                if form.is_valid():

                    profile = form.save(commit=False)
                    profile.user = user_profile
                    profile.save()



            return HttpResponseRedirect(f'/?error={error}')

class LoginView(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        else:
            return render(request,'video_tube/login.html')
    def post(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        else:
            if 'login' in request.POST:
                user_name=request.POST.get('user_name').strip()
                user_password=request.POST.get('user_password').strip()
                user=authenticate(request,username=user_name,password=user_password)

                if user is not None:
                    login(request,user)
                    return redirect('/')
                else:

                    messages.warning(request, 'Username Or Password not matched.')
                    return HttpResponseRedirect('/login/')


@login_required(login_url='/login/')
def logoutView(request):
    logout(request)
    return HttpResponseRedirect('/login/')

class SignUpView(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        else:
            context={
                'user_form':UserCreateForm()
            }
            return render(request,'video_tube/signup.html',context)
    def post(self,request,*args,**kwargs):
        print(request.POST)
        user=UserCreateForm(request.POST)
        if user.is_valid():
            user.save()
            return HttpResponseRedirect('/login')
        else:
            context={
                'errors':user.errors
            }
            return render(request,'video_tube/signup.html',context)

video_tube/templates/video_tube/category_wise.html
{% extends 'video_tube/main.html' %}
{% block title %}{{ videos.0.video.categorey }}{% endblock title %}
{% block content %}
<br>
    {% if not videos%}
<div class="containe-fluid" style="margin-top: 20px;">
    <div class="row">
        <div class="col-md-12 col-xs-12 col-lg-12 col-sm-12">
            <h2 class="text-warning text-center">There is no video is this categorey ! Add a video + </h2>
        </div>

    </div>

</div>
    {% endif %}
<div class="container-fluid" style="margin-top: 10px!important;">
    <div class="row">
        {% for v in videos %}

        <div class="col-md-4 col-lg-4 col-xs-12 col-sm-12">
            <div class="card border-warning mb-3 bg-dark" style="">
              <div class=""><a href="/video/id={{ v.video.id }}">
<img src="/{{ v.video.thumbnail.url }}" height="220px" width="100%"/>
                 </div>
                <div style="display: inline-flex">
                <div style="float: left;margin-top: 20px!important;margin-left: 6px!important;">
                    <a href="/user/id={{ v.video.user.user.id }}"><button style="margin-left:6px!important;border-radius: 50%!important;" class="btn btn-outline-warning my-2 my-sm-0" type="button"><img src="/{{ v.video.user.image.url }}" height="30px" width="30px"/></button></a>
                 </div>
                 <div style='float:right;' class="card-header text-white">
                     {{ v.video.title|slice:":33"  }}... <br><span style="margin-left:0px;">{{ v.views }} Views . {{ v.likes }} Likes</span>
                 </div>
                </div>
            </div>

        </div></a>
        {% endfor %}

    </div>

</div>

{% endblock content %}

video_tube/templates/video_tube/home.html
{% extends 'video_tube/main.html' %}
{% block title %}VTube{% endblock title %}
{% block content %}
<br>
<div class="container-fluid" style="margin-left: 0px!important;margin-right: 0px!important;">
    <div class="row justify-content-center text-center">
        {% for category in categories %}
        <a href="categorey/id={{ category.id }}"><button type="button" class="btn btn-warning text-dark " style="font-weight:700;border-radius: 30px;margin-right: 5px;margin-top: 5px;  ">{{ category.name }}</button></a>
         {% endfor %}
    </div>
</div>
<div class="container-fluid" style="margin-top: 10px!important;">
    <div class="row">
        {% for v in videos %}
        <div class="col-md-4 col-lg-4 col-xs-12 col-sm-12">
            <div class="card border-warning mb-3 bg-dark" style="">
              <div class=""><a href="/video/id={{ v.video.id }}">
<img src="{{ v.video.thumbnail.url }}" height="220px" width="100%"/>
                 </div>
                <div style="display: inline-flex">
                <div style="float: left;margin-top: 20px!important;margin-left: 6px!important;">
                    <a href="/user/id={{ v.video.user.user.id }}"><button style="margin-left:6px!important;border-radius: 50%!important;margin-top: 10px!important;" class="btn btn-outline-warning my-2 my-sm-0" type="button"><img src="{{ v.video.user.image.url }}" height="30px" width="30px"/></button></a>
                 </div>
                 <div style='float:right;' class="card-header text-white">
                     {{ v.video.title|slice:":33"  }}... <br><span style="margin-left:0px;">{{ v.views }} Views . {{ v.likes }} Likes <br>Upload By {{ v.video.user.user.username|slice:":10" }}</span>
                 </div>
                </div>
            </div>

        </div></a>
        {% endfor %}

    </div>

</div>

{% endblock content %}

video_tube/templates/video_tube/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Login</title>
    <!--BootStrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--End of Bootstrap CSS-->
    <!--FontAwesome Icons Link-->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--End of FontAwesome Icons Link-->

    <style>
a{
    text-decoration: none!important;
}
.lab{
    color:#ffc107;
}
.modal-body>p{
    color:#FFC107;
}
#id_thumbnail{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
#id_image{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
.form-control:focus {
    color: #ffc107;

    background-color: transparent;
    border-color: #ffc107ed;
    outline: 0;
    box-shadow: 0 0 0 0.2rem #ffc107;
}
#id_video{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
.form-control{
    border-radius: 20px;
    border-width: 6px;
    background-color: transparent;
    color: #ffc107;
    border-color: #FFC107!important;
}
.navbar {

    box-shadow: 0px 0px 20px 2px #0000001f;
}
    </style>
</head>
<body class="bg-dark">
<!--Start of Navbar-->

<div class="container-fluid" style="margin-top:120px!important;">
    <div class="row justify-content-center text-center">
        <div class="col-xs-8 col-sm-8 col-lg-4 col-md-4">

        {% if messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                   {% for message in messages %}

                      <i>{{ message }}</i>
                {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endif %}
            <div>
                <img src="{% static 'video_tube/ic.png'  %}" height="80" width="100"/>
                <form method="post" action="">
                    {% csrf_token %}
                    <label class="lab" for="user_name"><i>Enter Your Username</i> </label>
                    <input type="text" name="user_name" class="form-control">
                    <label class="lab" for="user_password"><i>Enter Your Password</i></label>
                    <input type="password" name="user_password" class="form-control">
                    <button type="submit" name="login" class="btn btn-warning" style="margin-top: 10px;padding-left: 30px;padding-right: 30px;font-weight: 900;border-radius: 10px">Login</button>
                    <a href="/signup/" style="text-decoration: underline!important;color: #ffc107;"><p class="lab">Sign Up</p></a>
                    <p style="color:#ffc107;margin-top: 20px">&copy; Copyright by Waseem</p>
                </form>
            </div>

        </div>

    </div>

</div>

<!--Bootstrap js/jquery-->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!--End of Bootstrap js/jquery-->
</body>
</html>

video_tube/templates/video_tube/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <!--BootStrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--End of Bootstrap CSS-->
    <!--FontAwesome Icons Link-->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--End of FontAwesome Icons Link-->
    {% block script %}{% endblock script %}
    <style>
a{
    text-decoration: none!important;
}
.modal-body>p{
    color:#FFC107;
}
#id_thumbnail{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
#id_image{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
.form-control:focus {
    color: #ffc107;

    background-color: transparent;
    border-color: #ffc107ed;
    outline: 0;
    box-shadow: 0 0 0 0.2rem #ffc107;
}
#id_video{
    border-style: solid;
    border-radius: 20px;
    border-width: 2px;
    outline:none;
}
.form-control{
    border-radius: 20px;
    border-width: 2px;
    background-color: transparent;
    color: white;
    border-color: #FFC107!important;
}
.navbar {

    box-shadow: 0px 0px 20px 2px #0000001f;
}
    </style>
</head>
<body class="bg-dark">
<!--Start of Navbar-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'video_tube:home' %}">
    <img src="{% static 'video_tube/ic.png' %}" width="100" height="70" class="d-inline-block align-top" style="margin-top: -10px!important;margin-bottom: -5px!important;margin-left:0px" alt="">

  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button style="margin-right: 6px!important;border-radius: 30px!important;" class="btn btn-outline-warning my-2 my-sm-0" type="button" data-toggle="modal" data-target="#addVideo"><i class="fa fa-plus"></i></button>
      <a href="/profile/"><button style="margin-left:6px!important;border-radius: 30px!important;" class="btn btn-outline-warning my-2 my-sm-0" type="button" ><i class="fa fa-user"></i></button></a>

    </form>
  </div>
</nav>
<!--End of Navbar-->
{% block content %}{% endblock content %}
<!--Add Video Model-->
 <div class="modal fade " id="addVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog " role="document">
    <div class="modal-content  bg-dark">
      <div class="modal-header">
        <h5 class="modal-title text-warning">Add Your Video</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span class="" aria-hidden="true">&times;</span>
        </button>
      </div>
        <form enctype="multipart/form-data" action="{% url 'video_tube:upload' %}" method="post">
      <div class="modal-body">


              {% csrf_token %}
          {{ video_form.as_p}}

      </div>
      <div class="modal-footer">
        <button name="upload" type="submit" class="btn btn-warning text-white" style="border-radius: 30px;font-weight: 500">Upload</button>
        <button type="button" class="btn btn-danger" style="border-radius: 30px;font-weight: 500" data-dismiss="modal">Close</button>
      </div>
        </form>
    </div>
  </div>
</div>
<!--End of Add Video Model-->
<!--Add Login SignUP Model-->
 <div class="modal fade " id="loginSignUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog " role="document">
    <div class="modal-content  bg-dark">
      <div class="modal-header">
        <h5 class="modal-title text-warning">Login / Logout</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          <span class="" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-warning">Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning text-white" style="border-radius: 30px;font-weight: 500">Upload</button>
        <button type="button" class="btn btn-danger" style="border-radius: 30px;font-weight: 500" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!--End of Login/Signup Model-->
<div class="container-fluid">
    <div class="footer text-warning" style="position:relative;top: 0px;color:white;text-align: center;font-size: 17px;font-weight: 400">
        <div>
            <p>&copy; Copyright by Waseem</p>
        </div>

    </div>

</div>
<!--Bootstrap js/jquery-->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!--End of Bootstrap js/jquery-->
</body>
</html>